import type { Metadata } from 'next';
import {
  Fira_Code,
  Geist,
  Geist_Mono,
  Inter,
  Playfair_Display,
} from 'next/font/google';
import './globals.css';
import { StoreProvider } from '../global/store/StoreContext';
import StoreProviderWrapper from '@/global/store/StoreProviderWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const interSans = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const Fira = Fira_Code({
  variable: '--font-Fira-Code',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Dokuwa's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html id='html-head' lang='en'>
      <body
        className={`${geistSans.variable} ${interSans.variable} ${Fira.variable} $ ${geistMono.variable} antialiased`}>
        {/* <StoreProviderWrapper>{children}</StoreProviderWrapper> */}
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
